version: '3.8'
services:
  money-app-dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 54321
      POSTGRES_DB: money-dev
    networks:
      - money-app
networks:
  money-app:
